### PR TITLE
Add new class diagram picture and xml. #3

### PR DESCRIPTION
**Pull request by oskstr**
Add a new class diagram with updated classes as well as the
corresponding .xml file.

### CODE REVIEW

**Review by kittytinythai — CHANGES_REQUESTED** [review]
I have some feedback:
- Make the diagram color coordinated
- What does the arrow between *Position* and *Drawable* mean? This class has [arrow] this interface?
- (suggestion) Maybe add *Box* and *Node* classes?

**Comment by oskstr** [comment]
Fair enough! I tried to add colours but I couldn't make it work. The arrow you're referring to is for an inner class, might be overkill. About the *Box* and *Node* classes, how do you think they should be? Subclasses of objects with some more properties?

**Comment by oskstr** [comment]
screen shot 2018-05-02 at 20 11 20

This is what happens when I try to add a colour. Some kind of white gap.

**Comment by kittytinythai** [comment]
Strange ...🤔 I suggest you change the color anyway, and let's clean it up later 😉

**Comment by oskstr** [comment]
Sure! Green for abstract, yellow for normal classes and grey for interfaces?

**Comment by kittytinythai** [comment]
Looks good!

**Review by kittytinythai — APPROVED** [review]

**Pull request merged**
